//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APILiczniki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Klienci
    {
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string ulica { get; set; }
        public string nume_budynku { get; set; }
        public string miejscowosc { get; set; }
        public string kod_pocztowy { get; set; }
        public Nullable<int> liczniki_id { get; set; }
    
        public virtual Liczniki Liczniki { get; set; }
    }
}
