//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APILiczniki
{
    using System;
    using System.Collections.Generic;
    
    public partial class Liczniki
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Liczniki()
        {
            this.Klienci = new HashSet<Klienci>();
        }
    
        public int id { get; set; }
        public string numer { get; set; }
        public string model { get; set; }
        public string producent { get; set; }
        public double stan { get; set; }
        public string taryfa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Klienci> Klienci { get; set; }
    }
}
